language: python
python:
- '3.6'
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_cd07f8c30fea_key -iv $encrypted_cd07f8c30fea_iv
  -in google_cloud_credentials.json.enc -out google_cloud_credentials.json -d
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database test_curate;' -U postgres
script:
- python manage.py test
deploy:
  provider: gae
  keyfile: google_cloud_credentials.json
  project: curate-science-216207
env:
  global:
    secure: i184MtjndRocoalJRVo/Heui4a/ly51epiPHFmyWjCZkp7NxwRTiOAq+DxVZlP4wivpBm31dzUPjrsdTpxktQJS2QpM5yZEpR7lSEsCaHk7yq/Zstdxn9eM5erVnxlnlAmR/G/jAO4w4Mv2ogTmrqjmS8Nv/rXV40FL1r3muP6JpR89yyUyH5TRyKLMeldavDXIap/TNm2u01J3ISHyqHsWtrjrexdtaSFLtLpklPp5AoEvmcVz9SrXBVFTALqxIgjwqKMAUw4COziP84ZQqzCtXV9a2g8jqLwsAV0lHwFLlzmmtwIYK7mywBPaEo3pCx0l67BKjklA2iGdtZvGWM140QfoaDO9vvtEyrHIYOl59yasOp9WZFPnnjOLJOR92wmTsQp7L1sprvJfVyQ9KzozgGMy9fYWuvICIUbemPGTZFfNSmVb/TT/jkH+Qa4dz7xQDrRiVtLjxCoQ06nFWlxDfeVGlE7O0c58J/tyrB0SfKLSqEnsr1jAG4Ayiov2zUgOXvCUJJHSU1/MlmwR8HhVluhXvrdCeozWPYkVBUJoLdHpnJ3LUy6MRV5yU5NU4hMuu2exApgE209zLPkObu/j6UmLlkDTkiaXHG5k3pRqjZ/xJO8XHheZcTl0L9ewh9jczr9zqXflsWJzXaoZCdkTEEHisn61n6gHNsEt3W0s=
